### PR TITLE
chore: fixup release instructions for pushing tags

### PR DESCRIPTION
**Pull request by gregmagolan**
# Description

Current instructions are incorrect.

# Type of change

- [x] Documentation (updates to documentation or READMEs)

### CODE REVIEW

**Review by alexeagle — COMMENTED** [review]
What's wrong with that bash shorthand notation? It means "last argument of prior command"

**Comment by gregmagolan** [comment]
> What's wrong with that bash shorthand notation? It means "last argument of prior command"

I don't know. It doesn't work for me.

```
gregs-mbp:aspect-cli greg$ git tag 6.6.6
gregs-mbp:aspect-cli greg$ echo $!
76802
```

Maybe it is linux specific?

**Comment by gregmagolan** [comment]
On noes... the stupid failing `git describe --tags` is back again,

```
//release/brew/tests:version_file_with_stamp_test                        FAILED in 0.3s
  /home/runner/.cache/bazel/_bazel_runner/8e9f7bf5c7ea7145245717c620f4b2bc/execroot/build_aspect_cli/bazel-out/k8-fastbuild/testlogs/release/brew/tests/version_file_with_stamp_test/test.log
```

**Comment by gregmagolan** [comment]
Oh I see... the current token `$!` is last PID.

Last arg is either `!$` or `$_`... Updating to `$_` since `!$` is too easy to mixup with `$!` at a glance.

**Review by alexeagle — APPROVED** [review]

**Pull request merged**
